[project]
name = "app"
version = "0.1.0"
requires-python = "==3.12.*"
classifiers = [
  "Private :: Do Not Upload",
]
dependencies = [
    "fastapi==0.109.0",
    "pydantic==2.5.3",
    "uvicorn==0.27.0",
    "werkzeug>=1.0.1",
]
